#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo '
╔════════════════════════════════════════════════════╗
╠════════════════════════════════════════════════════╣
║                                                    ║
║             This image is deprecated.              ║
║      We will not offer support for this image      ║
║            and it will not be updated.             ║
║                                                    ║
╠════════════════════════════════════════════════════╣
╚════════════════════════════════════════════════════╝

Due to lack of developers, and issues with maintaining status quo, upstream has decided to retire the project.

══════════════════════════════════════════════════════'
