#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -n ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            cd /app/readarr/bin /app/readarr/bin/Readarr \
            -nobrowser -data=/config
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            cd /app/readarr/bin s6-setuidgid abc /app/readarr/bin/Readarr \
            -nobrowser -data=/config
fi
