#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
        cd /app/readarr/bin s6-setuidgid abc /app/readarr/bin/Readarr \
        -nobrowser -data=/config
